import type {
  BuildThreadPageLayoutPropsInput,
  ComposerDockProps,
} from './threadPageLayoutPropTypes'

export function buildThreadPageComposerDockProps(
  input: BuildThreadPageLayoutPropsInput,
): ComposerDockProps {
  return {
    accountEmail: input.accountEmail,
    activeComposerApproval: input.activeComposerApproval,
    activeComposerPanel: input.activeComposerPanel,
    activePendingTurn: input.activePendingTurn,
    approvalAnswers: input.approvalAnswers,
    approvalErrors: input.approvalErrors,
    approvalsCount: input.approvalsCount,
    autoPruneDays: input.autoPruneDays,
    compactDisabledReason: input.compactDisabledReason,
    compactFeedback: input.compactFeedback,
    compactPending: input.compactPending,
    composerActivityDetail: input.composerActivityDetail,
    composerActivityTitle: input.composerActivityTitle,
    composerAutocompleteIndex: input.composerAutocompleteIndex,
    composerAutocompleteSectionGroups: input.composerAutocompleteSectionGroups,
    composerDockRef: input.composerDockRef,
    composerDockMeasureRef: input.composerDockMeasureRef,
    composerInputRef: input.composerInputRef,
    composerPreferences: input.composerPreferences,
    composerStatusInfo: input.composerStatusInfo,
    composerStatusMessage: input.composerStatusMessage,
    composerStatusRetryLabel: input.composerStatusRetryLabel,
    contextWindow: input.contextWindow,
    customInstructions: input.customInstructions,
    desktopModelOptions: input.desktopModelOptions,
    fileSearchIsFetching: input.fileSearchIsFetching,
    hasUnreadThreadUpdates: input.hasUnreadThreadUpdates,
    interruptPending: input.interruptPending,
    isApprovalDialogOpen: input.isApprovalDialogOpen,
    isCommandAutocompleteOpen: input.isCommandAutocompleteOpen,
    isComposerLocked: input.isComposerLocked,
    isInterruptMode: input.isInterruptMode,
    isMentionAutocompleteOpen: input.isMentionAutocompleteOpen,
    isMobileViewport: input.isMobileViewport,
    isSendBusy: input.isSendBusy,
    isSkillAutocompleteOpen: input.isSkillAutocompleteOpen,
    isThreadProcessing: input.isThreadProcessing,
    isWaitingForThreadData: input.isWaitingForThreadData,
    maxWorktrees: input.maxWorktrees,
    mcpServerStates: input.mcpServerStates,
    mcpServerStatusLoading: input.mcpServerStatusLoading,
    message: input.message,
    mobileCollaborationModeOptions: input.mobileCollaborationModeOptions,
    mobileModelOptions: input.mobileModelOptions,
    mobilePermissionOptions: input.mobilePermissionOptions,
    mobileReasoningOptions: input.mobileReasoningOptions,
    modelsLoading: input.modelsLoading,
    onChangeApprovalAnswer: input.onChangeApprovalAnswer,
    onChangeCollaborationMode: input.onChangeCollaborationMode,
    onChangeComposerAutocompleteIndex: input.onChangeComposerAutocompleteIndex,
    onChangeComposerMessage: input.onChangeComposerMessage,
    onChangeModel: input.onChangeModel,
    onChangePermissionPreset: input.onChangePermissionPreset,
    onChangeReasoningEffort: input.onChangeReasoningEffort,
    onCloseComposerPanel: input.onCloseComposerPanel,
    onCompactSelectedThread: input.onCompactSelectedThread,
    onComposerKeyDown: input.onComposerKeyDown,
    onComposerSelect: input.onComposerSelect,
    onJumpToLatest: input.onJumpToLatest,
    onPrimaryComposerAction: input.onPrimaryComposerAction,
    onRespondApproval: input.onRespondApproval,
    onRetryComposerStatus: input.onRetryComposerStatus,
    onSelectComposerAutocompleteItem: input.onSelectComposerAutocompleteItem,
    onSubmit: input.onSubmit,
    percent: input.percent,
    rateLimits: input.rateLimits,
    rateLimitsError: input.rateLimitsError,
    rateLimitsLoading: input.rateLimitsLoading,
    resolvedThreadTokenUsage: input.resolvedThreadTokenUsage,
    respondingToApproval: input.respondingToApproval,
    responseTone: input.responseTone,
    reuseBranches: input.reuseBranches,
    runtimeStatus: input.runtimeStatus,
    selectedThread: input.selectedThread,
    selectedThreadId: input.selectedThreadId,
    sendButtonLabel: input.sendButtonLabel,
    shouldShowComposerSpinner: input.shouldShowComposerSpinner,
    showJumpToLatestButton: input.showJumpToLatestButton,
    showMentionSearchHint: input.showMentionSearchHint,
    showSkillSearchLoading: input.showSkillSearchLoading,
    totalTokens: input.totalTokens,
    workspaceId: input.workspaceId,
  }
}
