import { getErrorMessage } from '../../lib/error-utils'
import { i18n } from '../../i18n/runtime'
import type {
  BuildThreadPageRailLayoutPropsResult,
  ConfirmDialogProps,
  RailProps,
} from './threadPageLayoutPropTypes'
import type { BuildThreadPageRailLayoutPropsInput } from './threadPageLayoutInputTypes'

export function buildThreadPageRailLayoutProps(
  input: BuildThreadPageRailLayoutPropsInput,
): BuildThreadPageRailLayoutPropsResult {
  const railProps: RailProps = {
    botSendBinding: input.botSendBinding,
    botSendBindingPending: input.botSendBindingPending,
    botSendBots: input.botSendBots,
    botSendDeliveryTargets: input.botSendDeliveryTargets,
    botSendErrorMessage: input.botSendErrorMessage,
    botSendLoading: input.botSendLoading,
    botSendPending: input.botSendPending,
    botSendSelectedBotId: input.botSendSelectedBotId,
    botSendSelectedDeliveryTargetId: input.botSendSelectedDeliveryTargetId,
    botSendText: input.botSendText,
    command: input.command,
    commandRunMode: input.commandRunMode,
    commandCount: input.commandCount,
    deletePending: input.deletePending,
    deletingThreadId: input.deletingThreadId,
    editingThreadId: input.editingThreadId,
    editingThreadName: input.editingThreadName,
    isExpanded: input.isExpanded,
    isMobileViewport: input.isMobileViewport,
    isResizing: input.isResizing,
    isThreadToolsExpanded: input.isThreadToolsExpanded,
    isWorkbenchToolsExpanded: input.isWorkbenchToolsExpanded,
    latestTurnStatus: input.latestTurnStatus,
    lastTimelineEventTs: input.lastTimelineEventTs,
    loadedAssistantMessageCount: input.loadedAssistantMessageCount,
    contextUsagePercent: input.contextUsagePercent,
    contextWindow: input.contextWindow,
    loadedMessageCount: input.loadedMessageCount,
    loadedTurnCount: input.loadedTurnCount,
    liveThreadCwd: input.liveThreadCwd,
    loadedUserMessageCount: input.loadedUserMessageCount,
    pendingApprovalsCount: input.pendingApprovalsCount,
    rootPath: input.rootPath,
    runtimeRecoverySummary: input.runtimeRecoverySummary,
    runtimeConfigChangedAt: input.runtimeConfigChangedAt,
    runtimeConfigLoadStatus: input.runtimeConfigLoadStatus,
    hookConfiguration: input.hookConfiguration,
    hookConfigurationError: input.hookConfigurationError,
    hookConfigurationLoading: input.hookConfigurationLoading,
    runtimeRestartRequired: input.runtimeRestartRequired,
    restartRuntimePending: input.restartRuntimePending,
    runtimeStartedAt: input.runtimeStartedAt,
    runtimeUpdatedAt: input.runtimeUpdatedAt,
    selectedThread: input.selectedThread,
    shellEnvironmentInfo: input.shellEnvironmentInfo,
    shellEnvironmentSummary: input.shellEnvironmentSummary,
    shellEnvironmentWarning: input.shellEnvironmentWarning,
    startCommandModeDisabled: input.startCommandModeDisabled,
    startCommandPending: input.startCommandPending,
    streamState: input.streamState,
    surfacePanelView: input.surfacePanelView,
    hookRuns: input.hookRuns,
    hookRunsError: input.hookRunsError,
    hookRunsLoading: input.hookRunsLoading,
    turnPolicyDecisions: input.turnPolicyDecisions,
    turnPolicyDecisionsError: input.turnPolicyDecisionsError,
    turnPolicyDecisionsLoading: input.turnPolicyDecisionsLoading,
    turnPolicyMetrics: input.turnPolicyMetrics,
    turnPolicyMetricsError: input.turnPolicyMetricsError,
    turnPolicyMetricsLoading: input.turnPolicyMetricsLoading,
    threadCount: input.threadCount,
    timelineItemCount: input.timelineItemCount,
    totalTokens: input.totalTokens,
    totalMessageCount: input.totalMessageCount,
    totalTurnCount: input.totalTurnCount,
    turnCount: input.turnCount,
    workspaceName: input.workspaceName,
    onArchiveToggle: input.onArchiveToggle,
    onBeginRenameThread: input.onBeginRenameThread,
    onBindThreadBotChannel: input.onBindThreadBotChannel,
    onCancelRenameThread: input.onCancelRenameThread,
    onChangeBotSendSelectedBotId: input.onChangeBotSendSelectedBotId,
    onChangeBotSendSelectedDeliveryTargetId: input.onChangeBotSendSelectedDeliveryTargetId,
    onChangeBotSendText: input.onChangeBotSendText,
    onChangeCommand: input.onChangeCommand,
    onChangeCommandRunMode: input.onChangeCommandRunMode,
    onChangeEditingThreadName: input.onChangeEditingThreadName,
    onCloseWorkbenchOverlay: input.onCloseWorkbenchOverlay,
    onDeleteThread: input.onDeleteThread,
    onDeleteThreadBotBinding: input.onDeleteThreadBotBinding,
    onHideSurfacePanel: input.onHideSurfacePanel,
    onInspectorResizeStart: input.onInspectorResizeStart,
    onOpenInspector: input.onOpenInspector,
    onOpenSurfacePanel: input.onOpenSurfacePanel,
    onRestartRuntime: input.onRestartRuntime,
    onResetInspectorWidth: input.onResetInspectorWidth,
    onSendBotMessage: input.onSendBotMessage,
    onStartCommand: input.onStartCommand,
    onSubmitRenameThread: input.onSubmitRenameThread,
    onToggleThreadToolsExpanded: input.onToggleThreadToolsExpanded,
    onToggleWorkbenchToolsExpanded: input.onToggleWorkbenchToolsExpanded,
  }

  const confirmDialogProps: ConfirmDialogProps | null = input.confirmingThreadDelete
    ? {
        confirmLabel: i18n._({
          id: 'Delete Thread',
          message: 'Delete Thread',
        }),
        description: i18n._({
          id: 'This removes the thread from this workspace list and clears its active UI state.',
          message: 'This removes the thread from this workspace list and clears its active UI state.',
        }),
        error: input.confirmDialogError
          ? getErrorMessage(input.confirmDialogError)
          : null,
        isPending: input.deletePending,
        onClose: input.onCloseDeleteThreadDialog,
        onConfirm: input.onConfirmDeleteThreadDialog,
        subject: input.confirmingThreadDelete.name,
        title: i18n._({
          id: 'Delete Thread?',
          message: 'Delete Thread?',
        }),
      }
    : null

  return {
    confirmDialogProps,
    railProps,
  }
}
