import { useThreadComposerActions } from './useThreadComposerActions'
import { useThreadPageActions } from './useThreadPageActions'
import { useThreadPageComposerCallbacks } from './useThreadPageComposerCallbacks'
import type {
  ThreadPageControllerActions,
  UseThreadPageControllerActionsInput,
} from './threadPageControllerLayoutTypes'

export function useThreadPageControllerActions({
  controllerState,
  dataState,
  displayState,
  mutationState,
  panelState,
  railState,
  statusState,
  viewportState,
}: UseThreadPageControllerActionsInput): ThreadPageControllerActions {
  const activeSelectedThreadId =
    dataState.resolvedSelectedThreadId ?? controllerState.selectedThreadId

  const composerActions = useThreadComposerActions({
    activeComposerMatchMode: controllerState.activeComposerMatch?.mode,
    applyComposerMessage: controllerState.applyComposerMessage,
    clearComposerTriggerToken: controllerState.clearComposerTriggerToken,
    composerAutocompleteItem: panelState.composerAutocompleteItem,
    composerAutocompleteItemsLength: panelState.composerAutocompleteItems.length,
    dismissComposerAutocomplete: controllerState.dismissComposerAutocomplete,
    insertComposerText: controllerState.insertComposerText,
    isCommandAutocompleteOpen: controllerState.isCommandAutocompleteOpen,
    isMentionAutocompleteOpen: controllerState.isMentionAutocompleteOpen,
    isSkillAutocompleteOpen: controllerState.isSkillAutocompleteOpen,
    message: controllerState.message,
    sendError: controllerState.sendError,
    setActiveComposerPanel: controllerState.setActiveComposerPanel,
    setComposerAutocompleteIndex: controllerState.setComposerAutocompleteIndex,
    setComposerCaret: controllerState.setComposerCaret,
    setComposerCommandMenu: controllerState.setComposerCommandMenu,
    setComposerPreferences: controllerState.setComposerPreferences,
    setDismissedComposerAutocompleteKey: controllerState.setDismissedComposerAutocompleteKey,
    setMessage: controllerState.setMessage,
    setSendError: controllerState.setSendError,
    supportsPlanMode: controllerState.supportsPlanMode,
  })

  const pageActions = useThreadPageActions({
    botSendBots: dataState.botSendBotsQuery.data ?? [],
    botSendSelectedBotId: controllerState.botSendSelectedBotId,
    botSendSelectedDeliveryTargetId: controllerState.botSendSelectedDeliveryTargetId,
    botSendText: controllerState.botSendText,
    bindThreadBotChannelMutation: mutationState.bindThreadBotChannelMutation,
    archiveThreadMutation: mutationState.archiveThreadMutation,
    clearCompletedCommandSessions: controllerState.clearCompletedCommandSessions,
    closeDeleteThreadDialog: railState.handleCloseDeleteThreadDialog,
    command: controllerState.command,
    commandRunMode: controllerState.commandRunMode,
    commandSessions: dataState.commandSessions,
    compactDisabledReason: statusState.compactDisabledReason,
    compactThreadMutation: mutationState.compactThreadMutation,
    composerPreferences: controllerState.composerPreferences,
    confirmingThreadDelete: railState.confirmingThreadDelete,
    deleteThreadMutation: mutationState.deleteThreadMutation,
    deleteThreadBotBindingMutation: mutationState.deleteThreadBotBindingMutation,
    editingThreadName: railState.editingThreadName,
    fullTurnItemContentOverridesById: controllerState.fullTurnItemContentOverridesById,
    fullTurnItemOverridesById: controllerState.fullTurnItemOverridesById,
    fullTurnItemRetainCountById: controllerState.fullTurnItemRetainCountById,
    fullTurnOverridesById: controllerState.fullTurnOverridesById,
    fullTurnRetainCountById: controllerState.fullTurnRetainCountById,
    historicalTurns: controllerState.historicalTurns,
    interruptTurnMutation: mutationState.interruptTurnMutation,
    invalidateThreadQueries: mutationState.invalidateThreadQueries,
    isInterruptMode: statusState.isInterruptMode,
    isLoadingOlderTurns: controllerState.isLoadingOlderTurns,
    message: controllerState.message,
    oldestDisplayedTurnId: displayState.oldestDisplayedTurnId,
    queryClient: controllerState.queryClient,
    removeCommandSession: controllerState.removeCommandSession,
    updateCommandSession: controllerState.updateCommandSession,
    renameThreadMutation: mutationState.renameThreadMutation,
    requestDeleteSelectedThread: railState.handleDeleteSelectedThread,
    respondApprovalMutation: mutationState.respondApprovalMutation,
    scrollThreadToLatest: viewportState.scrollThreadToLatest,
    selectedCommandSession: displayState.selectedCommandSession,
    selectedProcessId: controllerState.selectedProcessId,
    selectedThread: dataState.selectedThread,
    selectedThreadId: activeSelectedThreadId,
    sendBotDeliveryTargetOutboundMessageMutation:
      mutationState.sendBotDeliveryTargetOutboundMessageMutation,
    setActiveComposerPanel: controllerState.setActiveComposerPanel,
    setApprovalAnswers: controllerState.setApprovalAnswers,
    setAuthRecoveryRequestedAt: controllerState.setAuthRecoveryRequestedAt,
    setBotSendError: controllerState.setBotSendError,
    setComposerCaret: controllerState.setComposerCaret,
    setComposerCommandMenu: controllerState.setComposerCommandMenu,
    setDismissedComposerAutocompleteKey: controllerState.setDismissedComposerAutocompleteKey,
    setFullTurnItemContentOverridesById: controllerState.setFullTurnItemContentOverridesById,
    setFullTurnItemOverridesById: controllerState.setFullTurnItemOverridesById,
    setFullTurnItemRetainCountById: controllerState.setFullTurnItemRetainCountById,
    setFullTurnOverridesById: controllerState.setFullTurnOverridesById,
    setFullTurnRetainCountById: controllerState.setFullTurnRetainCountById,
    setHasMoreHistoricalTurnsBefore: controllerState.setHasMoreHistoricalTurnsBefore,
    setHistoricalTurns: controllerState.setHistoricalTurns,
    setCommandRunMode: controllerState.setCommandRunMode,
    setIsTerminalDockExpanded: controllerState.setIsTerminalDockExpanded,
    setIsLoadingOlderTurns: controllerState.setIsLoadingOlderTurns,
    setMessage: controllerState.setMessage,
    setSelectedProcessId: controllerState.setSelectedProcessId,
    setSendError: controllerState.setSendError,
    setThreadTurnWindowSize: controllerState.setThreadTurnWindowSize,
    startCommandMutation: mutationState.startCommandMutation,
    startTurnMutation: mutationState.startTurnMutation,
    threadDetail: dataState.liveThreadDetail ?? dataState.threadDetailQuery.data,
    stdinValue: controllerState.stdinValue,
    terminateCommandMutation: mutationState.terminateCommandMutation,
    threadShellCommandMutation: mutationState.threadShellCommandMutation,
    unarchiveThreadMutation: mutationState.unarchiveThreadMutation,
    updatePendingTurn: controllerState.updatePendingTurn,
    workspaceId: controllerState.workspaceId,
    writeCommandMutation: mutationState.writeCommandMutation,
  })

  const composerCallbacks = useThreadPageComposerCallbacks({
    hasAccountError: Boolean(dataState.accountQuery.error),
    queryClient: controllerState.queryClient,
    requiresOpenAIAuth: statusState.requiresOpenAIAuth,
    sendError: controllerState.sendError,
    setActiveComposerPanel: controllerState.setActiveComposerPanel,
    setComposerPreferences: controllerState.setComposerPreferences,
    setSendError: controllerState.setSendError,
    workspaceId: controllerState.workspaceId,
  })

  return {
    composerActions,
    composerCallbacks,
    pageActions,
  }
}
