package feishutools

type toolDefinition struct {
	ToolName    string
	Title       string
	Description string
	Stage       string
	RiskLevel   string
	ActionKeys  []string
}

type capabilityCategoryDefinition struct {
	ID          string
	Title       string
	Description string
	ToolNames   []string
}

var capabilityCategories = []capabilityCategoryDefinition{
	{
		ID:          "docs",
		Title:       "Docs",
		Description: "Search, read, create, and update Feishu documents and Wiki content.",
		ToolNames: []string{
			"feishu_search_doc_wiki",
			"feishu_fetch_doc",
			"feishu_create_doc",
			"feishu_update_doc",
			"feishu_wiki_space",
			"feishu_wiki_space_node",
		},
	},
	{
		ID:          "messenger",
		Title:       "Messenger",
		Description: "Read chat history, send/reply as the user, and download thread attachments.",
		ToolNames: []string{
			"feishu_im_user_search_messages",
			"feishu_im_user_get_messages",
			"feishu_im_user_get_thread_messages",
			"feishu_im_user_fetch_resource",
			"feishu_im_user_message",
		},
	},
	{
		ID:          "directory",
		Title:       "Directory",
		Description: "Resolve users, chats, and members before taking action in threads.",
		ToolNames: []string{
			"feishu_search_user",
			"feishu_get_user",
			"feishu_chat",
			"feishu_chat_members",
		},
	},
	{
		ID:          "calendar",
		Title:       "Calendar",
		Description: "Check availability and manage events from thread output.",
		ToolNames: []string{
			"feishu_calendar_calendar",
			"feishu_calendar_freebusy",
			"feishu_calendar_event",
			"feishu_calendar_event_attendee",
		},
	},
	{
		ID:          "tasks",
		Title:       "Tasks",
		Description: "Create and update Feishu tasks from thread decisions.",
		ToolNames: []string{
			"feishu_task_task",
			"feishu_task_tasklist",
			"feishu_task_section",
			"feishu_task_subtask",
			"feishu_task_comment",
		},
	},
	{
		ID:          "sheets",
		Title:       "Sheets",
		Description: "Create, read, edit, search, and export Feishu spreadsheets.",
		ToolNames: []string{
			"feishu_sheet",
		},
	},
	{
		ID:          "base",
		Title:       "Base",
		Description: "Create and manage Feishu Base apps, tables, fields, records, and views.",
		ToolNames: []string{
			"feishu_bitable_app",
			"feishu_bitable_app_table",
			"feishu_bitable_app_table_field",
			"feishu_bitable_app_table_record",
			"feishu_bitable_app_table_view",
		},
	},
	{
		ID:          "drive",
		Title:       "Drive",
		Description: "List, inspect, comment on, and attach media to Feishu Drive documents.",
		ToolNames: []string{
			"feishu_drive_file",
			"feishu_doc_comments",
			"feishu_doc_media",
		},
	},
}

var toolDefinitions = map[string]toolDefinition{
	"feishu_search_doc_wiki": {
		ToolName:    "feishu_search_doc_wiki",
		Title:       "Search Docs and Wiki",
		Description: "Search Feishu documents and Wiki nodes from a thread.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_search_doc_wiki.search"},
	},
	"feishu_fetch_doc": {
		ToolName:    "feishu_fetch_doc",
		Title:       "Read Document",
		Description: "Read document content as Markdown.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_fetch_doc.default"},
	},
	"feishu_create_doc": {
		ToolName:    "feishu_create_doc",
		Title:       "Create Document",
		Description: "Create a new Feishu document from Markdown.",
		Stage:       "phase_1",
		RiskLevel:   "write",
		ActionKeys:  []string{"feishu_create_doc.default"},
	},
	"feishu_wiki_space": {
		ToolName:    "feishu_wiki_space",
		Title:       "Manage Wiki Space",
		Description: "List, inspect, and create Feishu Wiki spaces.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_wiki_space.list",
			"feishu_wiki_space.get",
			"feishu_wiki_space.create",
		},
	},
	"feishu_wiki_space_node": {
		ToolName:    "feishu_wiki_space_node",
		Title:       "Manage Wiki Space Node",
		Description: "List, inspect, create, move, and copy Feishu Wiki nodes.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_wiki_space_node.list",
			"feishu_wiki_space_node.get",
			"feishu_wiki_space_node.create",
			"feishu_wiki_space_node.move",
			"feishu_wiki_space_node.copy",
		},
	},
	"feishu_update_doc": {
		ToolName:    "feishu_update_doc",
		Title:       "Update Document",
		Description: "Append, overwrite, or target a specific range inside an existing document.",
		Stage:       "phase_1",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_update_doc.append_text",
			"feishu_update_doc.append",
			"feishu_update_doc.append_markdown",
			"feishu_update_doc.overwrite",
			"feishu_update_doc.replace_range",
			"feishu_update_doc.replace_all",
			"feishu_update_doc.insert_before",
			"feishu_update_doc.insert_after",
			"feishu_update_doc.delete_range",
		},
	},
	"feishu_im_user_search_messages": {
		ToolName:    "feishu_im_user_search_messages",
		Title:       "Search Messages",
		Description: "Search Feishu message history across chats.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_im_user_search_messages.default"},
	},
	"feishu_im_user_get_messages": {
		ToolName:    "feishu_im_user_get_messages",
		Title:       "Read Messages",
		Description: "Read group or direct-message history.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_im_user_get_messages.default"},
	},
	"feishu_im_user_get_thread_messages": {
		ToolName:    "feishu_im_user_get_thread_messages",
		Title:       "Read Thread Messages",
		Description: "Read replies inside a Feishu thread.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_im_user_get_thread_messages.default"},
	},
	"feishu_im_user_fetch_resource": {
		ToolName:    "feishu_im_user_fetch_resource",
		Title:       "Download Message Resource",
		Description: "Download files and images attached to messages.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_im_user_fetch_resource.default"},
	},
	"feishu_im_user_message": {
		ToolName:    "feishu_im_user_message",
		Title:       "Send User Message",
		Description: "Send or reply to Feishu IM messages as the authorized user.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_im_user_message.send",
			"feishu_im_user_message.reply",
		},
	},
	"feishu_search_user": {
		ToolName:    "feishu_search_user",
		Title:       "Search User",
		Description: "Find employees before assigning tasks or meetings.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_search_user.default"},
	},
	"feishu_get_user": {
		ToolName:    "feishu_get_user",
		Title:       "Get User",
		Description: "Load user profile details for a selected account.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_get_user.default", "feishu_get_user.basic_batch"},
	},
	"feishu_chat": {
		ToolName:    "feishu_chat",
		Title:       "Search Chat",
		Description: "Search or inspect Feishu chats.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_chat.search", "feishu_chat.get"},
	},
	"feishu_chat_members": {
		ToolName:    "feishu_chat_members",
		Title:       "List Chat Members",
		Description: "Resolve chat members before inviting or assigning work.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_chat_members.default"},
	},
	"feishu_calendar_freebusy": {
		ToolName:    "feishu_calendar_freebusy",
		Title:       "Check Free/Busy",
		Description: "Check attendee availability before creating events.",
		Stage:       "phase_1",
		RiskLevel:   "read",
		ActionKeys:  []string{"feishu_calendar_freebusy.list"},
	},
	"feishu_calendar_calendar": {
		ToolName:    "feishu_calendar_calendar",
		Title:       "Manage Calendar",
		Description: "List calendars, inspect a calendar, or resolve the user's primary calendar.",
		Stage:       "phase_2",
		RiskLevel:   "read",
		ActionKeys: []string{
			"feishu_calendar_calendar.list",
			"feishu_calendar_calendar.get",
			"feishu_calendar_calendar.primary",
		},
	},
	"feishu_calendar_event": {
		ToolName:    "feishu_calendar_event",
		Title:       "Manage Calendar Event",
		Description: "Create, search, update, delete, reply to, and expand Feishu calendar events.",
		Stage:       "phase_1",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_calendar_event.create",
			"feishu_calendar_event.list",
			"feishu_calendar_event.get",
			"feishu_calendar_event.patch",
			"feishu_calendar_event.delete",
			"feishu_calendar_event.search",
			"feishu_calendar_event.reply",
			"feishu_calendar_event.instances",
			"feishu_calendar_event.instance_view",
		},
	},
	"feishu_calendar_event_attendee": {
		ToolName:    "feishu_calendar_event_attendee",
		Title:       "Manage Event Attendees",
		Description: "Invite attendees and inspect RSVP state for a calendar event.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_calendar_event_attendee.create",
			"feishu_calendar_event_attendee.list",
		},
	},
	"feishu_task_task": {
		ToolName:    "feishu_task_task",
		Title:       "Manage Task",
		Description: "Create, read, list, and update Feishu tasks.",
		Stage:       "phase_1",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_task_task.create",
			"feishu_task_task.get",
			"feishu_task_task.list",
			"feishu_task_task.patch",
		},
	},
	"feishu_task_tasklist": {
		ToolName:    "feishu_task_tasklist",
		Title:       "Manage Task List",
		Description: "Create, inspect, list, update, and inspect tasks inside Feishu task lists.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_task_tasklist.create",
			"feishu_task_tasklist.get",
			"feishu_task_tasklist.list",
			"feishu_task_tasklist.tasks",
			"feishu_task_tasklist.patch",
			"feishu_task_tasklist.add_members",
		},
	},
	"feishu_task_section": {
		ToolName:    "feishu_task_section",
		Title:       "Manage Task Section",
		Description: "Create, inspect, list, update, and inspect tasks inside task sections.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_task_section.create",
			"feishu_task_section.get",
			"feishu_task_section.list",
			"feishu_task_section.patch",
			"feishu_task_section.tasks",
		},
	},
	"feishu_task_subtask": {
		ToolName:    "feishu_task_subtask",
		Title:       "Manage Subtask",
		Description: "Create subtasks and list subtasks attached to a task.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_task_subtask.create",
			"feishu_task_subtask.list",
		},
	},
	"feishu_task_comment": {
		ToolName:    "feishu_task_comment",
		Title:       "Manage Task Comment",
		Description: "Create, inspect, and list comments attached to Feishu tasks.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_task_comment.create",
			"feishu_task_comment.list",
			"feishu_task_comment.get",
		},
	},
	"feishu_sheet": {
		ToolName:    "feishu_sheet",
		Title:       "Manage Spreadsheet",
		Description: "Inspect, read, write, append, search, create, and export Feishu spreadsheets.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_sheet.info",
			"feishu_sheet.read",
			"feishu_sheet.write",
			"feishu_sheet.append",
			"feishu_sheet.find",
			"feishu_sheet.create",
			"feishu_sheet.export",
		},
	},
	"feishu_bitable_app": {
		ToolName:    "feishu_bitable_app",
		Title:       "Manage Base App",
		Description: "Create, inspect, list, update, or copy Feishu Base apps.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_bitable_app.create",
			"feishu_bitable_app.get",
			"feishu_bitable_app.list",
			"feishu_bitable_app.patch",
			"feishu_bitable_app.copy",
		},
	},
	"feishu_bitable_app_table": {
		ToolName:    "feishu_bitable_app_table",
		Title:       "Manage Base Table",
		Description: "Create, list, update, or batch create Feishu Base tables.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_bitable_app_table.create",
			"feishu_bitable_app_table.list",
			"feishu_bitable_app_table.patch",
			"feishu_bitable_app_table.batch_create",
		},
	},
	"feishu_bitable_app_table_field": {
		ToolName:    "feishu_bitable_app_table_field",
		Title:       "Manage Base Field",
		Description: "Create, list, update, or delete Feishu Base fields.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_bitable_app_table_field.create",
			"feishu_bitable_app_table_field.list",
			"feishu_bitable_app_table_field.update",
			"feishu_bitable_app_table_field.delete",
		},
	},
	"feishu_bitable_app_table_record": {
		ToolName:    "feishu_bitable_app_table_record",
		Title:       "Manage Base Record",
		Description: "Create, search, update, delete, and batch manage Feishu Base records.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_bitable_app_table_record.create",
			"feishu_bitable_app_table_record.list",
			"feishu_bitable_app_table_record.update",
			"feishu_bitable_app_table_record.delete",
			"feishu_bitable_app_table_record.batch_create",
			"feishu_bitable_app_table_record.batch_update",
			"feishu_bitable_app_table_record.batch_delete",
		},
	},
	"feishu_bitable_app_table_view": {
		ToolName:    "feishu_bitable_app_table_view",
		Title:       "Manage Base View",
		Description: "Create, inspect, list, or update Feishu Base views.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_bitable_app_table_view.create",
			"feishu_bitable_app_table_view.get",
			"feishu_bitable_app_table_view.list",
			"feishu_bitable_app_table_view.patch",
		},
	},
	"feishu_drive_file": {
		ToolName:    "feishu_drive_file",
		Title:       "Manage Drive File",
		Description: "List, inspect metadata, copy, and download Feishu Drive files.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_drive_file.list",
			"feishu_drive_file.get_meta",
			"feishu_drive_file.copy",
			"feishu_drive_file.move",
			"feishu_drive_file.delete",
			"feishu_drive_file.upload",
			"feishu_drive_file.download",
		},
	},
	"feishu_doc_comments": {
		ToolName:    "feishu_doc_comments",
		Title:       "Manage Document Comments",
		Description: "List, reply to, create, and resolve comments on Feishu documents.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_doc_comments.list",
			"feishu_doc_comments.list_replies",
			"feishu_doc_comments.create",
			"feishu_doc_comments.reply",
			"feishu_doc_comments.patch",
		},
	},
	"feishu_doc_media": {
		ToolName:    "feishu_doc_media",
		Title:       "Manage Document Media",
		Description: "Insert local media into documents or download existing document media and whiteboards.",
		Stage:       "phase_2",
		RiskLevel:   "write",
		ActionKeys: []string{
			"feishu_doc_media.insert",
			"feishu_doc_media.download",
		},
	},
}

var toolActionScopes = map[string][]string{
	"feishu_calendar_event.create": {"calendar:calendar.event:create", "calendar:calendar.event:update"},
	"feishu_calendar_event.list":   {"calendar:calendar.event:read"},
	"feishu_calendar_event.get":    {"calendar:calendar.event:read"},
	"feishu_calendar_event.patch":  {"calendar:calendar.event:update"},
	"feishu_calendar_event.delete": {"calendar:calendar.event:delete"},
	"feishu_calendar_event.search": {"calendar:calendar.event:read"},
	"feishu_calendar_event.reply":  {"calendar:calendar.event:reply"},
	"feishu_calendar_event.instances": {
		"calendar:calendar.event:read",
	},
	"feishu_calendar_event.instance_view": {
		"calendar:calendar.event:read",
	},
	"feishu_calendar_calendar.list": {"calendar:calendar:read"},
	"feishu_calendar_calendar.get":  {"calendar:calendar:read"},
	"feishu_calendar_calendar.primary": {
		"calendar:calendar:read",
	},
	"feishu_calendar_event_attendee.create": {"calendar:calendar.event:update"},
	"feishu_calendar_event_attendee.list":   {"calendar:calendar.event:read"},
	"feishu_calendar_freebusy.list":         {"calendar:calendar.free_busy:read"},
	"feishu_task_task.create":               {"task:task:write", "task:task:writeonly"},
	"feishu_task_task.get":                  {"task:task:read", "task:task:write"},
	"feishu_task_task.list":                 {"task:task:read", "task:task:write"},
	"feishu_task_task.patch":                {"task:task:write", "task:task:writeonly"},
	"feishu_task_tasklist.create":           {"task:tasklist:write"},
	"feishu_task_tasklist.get":              {"task:tasklist:read", "task:tasklist:write"},
	"feishu_task_tasklist.list":             {"task:tasklist:read", "task:tasklist:write"},
	"feishu_task_tasklist.tasks":            {"task:tasklist:read", "task:tasklist:write"},
	"feishu_task_tasklist.patch":            {"task:tasklist:write"},
	"feishu_task_tasklist.add_members": {
		"task:tasklist:write",
	},
	"feishu_task_section.create":  {"task:task"},
	"feishu_task_section.get":     {"task:task"},
	"feishu_task_section.list":    {"task:task"},
	"feishu_task_section.patch":   {"task:task"},
	"feishu_task_section.tasks":   {"task:task"},
	"feishu_task_subtask.create":  {"task:task:write"},
	"feishu_task_subtask.list":    {"task:task:read", "task:task:write"},
	"feishu_task_comment.create":  {"task:comment:write"},
	"feishu_task_comment.list":    {"task:comment:read", "task:comment:write"},
	"feishu_task_comment.get":     {"task:comment:read", "task:comment:write"},
	"feishu_chat.search":          {"im:chat:read"},
	"feishu_chat.get":             {"im:chat:read"},
	"feishu_chat_members.default": {"im:chat.members:read"},
	"feishu_im_user_fetch_resource.default": {
		"im:message.group_msg:get_as_user",
		"im:message.p2p_msg:get_as_user",
		"im:message:readonly",
	},
	"feishu_im_user_get_messages.default": {
		"im:chat:read",
		"im:message:readonly",
		"im:message.group_msg:get_as_user",
		"im:message.p2p_msg:get_as_user",
		"contact:contact.base:readonly",
		"contact:user.base:readonly",
	},
	"feishu_im_user_get_thread_messages.default": {
		"im:chat:read",
		"im:message:readonly",
		"im:message.group_msg:get_as_user",
		"im:message.p2p_msg:get_as_user",
		"contact:contact.base:readonly",
		"contact:user.base:readonly",
	},
	"feishu_im_user_search_messages.default": {
		"im:chat:read",
		"im:message:readonly",
		"im:message.group_msg:get_as_user",
		"im:message.p2p_msg:get_as_user",
		"contact:contact.base:readonly",
		"contact:user.base:readonly",
		"search:message",
	},
	"feishu_im_user_message.send":   {"im:message", "im:message.send_as_user"},
	"feishu_im_user_message.reply":  {"im:message", "im:message.send_as_user"},
	"feishu_wiki_space.list":        {"wiki:space:retrieve"},
	"feishu_wiki_space.get":         {"wiki:space:read"},
	"feishu_wiki_space.create":      {"wiki:space:write_only"},
	"feishu_wiki_space_node.list":   {"wiki:node:retrieve"},
	"feishu_wiki_space_node.get":    {"wiki:node:read"},
	"feishu_wiki_space_node.create": {"wiki:node:create"},
	"feishu_wiki_space_node.move":   {"wiki:node:move"},
	"feishu_wiki_space_node.copy":   {"wiki:node:copy"},
	"feishu_search_doc_wiki.search": {"search:docs:read"},
	"feishu_get_user.basic_batch":   {"contact:user.basic_profile:readonly"},
	"feishu_get_user.default":       {"contact:contact.base:readonly", "contact:user.base:readonly"},
	"feishu_search_user.default":    {"contact:user:search"},
	"feishu_create_doc.default": {
		"board:whiteboard:node:create",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
		"wiki:node:create",
		"wiki:node:read",
		"docs:document.media:upload",
	},
	"feishu_fetch_doc.default": {"docx:document:readonly", "wiki:node:read"},
	"feishu_update_doc.append_text": {
		"board:whiteboard:node:create",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_update_doc.append": {
		"board:whiteboard:node:create",
		"docx:document.block:convert",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_update_doc.append_markdown": {
		"board:whiteboard:node:create",
		"docx:document.block:convert",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_update_doc.overwrite": {
		"board:whiteboard:node:create",
		"docx:document.block:convert",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_update_doc.replace_range": {
		"board:whiteboard:node:create",
		"docx:document.block:convert",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_update_doc.replace_all": {
		"board:whiteboard:node:create",
		"docx:document.block:convert",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_update_doc.insert_before": {
		"board:whiteboard:node:create",
		"docx:document.block:convert",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_update_doc.insert_after": {
		"board:whiteboard:node:create",
		"docx:document.block:convert",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_update_doc.delete_range": {
		"board:whiteboard:node:create",
		"docx:document:create",
		"docx:document:readonly",
		"docx:document:write_only",
	},
	"feishu_sheet.info": {"sheets:spreadsheet.meta:read", "sheets:spreadsheet:read"},
	"feishu_sheet.read": {"sheets:spreadsheet.meta:read", "sheets:spreadsheet:read"},
	"feishu_sheet.write": {
		"sheets:spreadsheet.meta:read",
		"sheets:spreadsheet:read",
		"sheets:spreadsheet:create",
		"sheets:spreadsheet:write_only",
	},
	"feishu_sheet.append": {
		"sheets:spreadsheet.meta:read",
		"sheets:spreadsheet:read",
		"sheets:spreadsheet:create",
		"sheets:spreadsheet:write_only",
	},
	"feishu_sheet.find":                            {"sheets:spreadsheet.meta:read", "sheets:spreadsheet:read"},
	"feishu_sheet.create":                          {"sheets:spreadsheet.meta:read", "sheets:spreadsheet:read", "sheets:spreadsheet:create", "sheets:spreadsheet:write_only"},
	"feishu_sheet.export":                          {"docs:document:export"},
	"feishu_bitable_app.create":                    {"base:app:create"},
	"feishu_bitable_app.get":                       {"base:app:read"},
	"feishu_bitable_app.list":                      {"space:document:retrieve"},
	"feishu_bitable_app.patch":                     {"base:app:update"},
	"feishu_bitable_app.copy":                      {"base:app:copy"},
	"feishu_bitable_app_table.create":              {"base:table:create"},
	"feishu_bitable_app_table.list":                {"base:table:read"},
	"feishu_bitable_app_table.patch":               {"base:table:update"},
	"feishu_bitable_app_table.batch_create":        {"base:table:create"},
	"feishu_bitable_app_table_field.create":        {"base:field:create"},
	"feishu_bitable_app_table_field.list":          {"base:field:read"},
	"feishu_bitable_app_table_field.update":        {"base:field:read", "base:field:update"},
	"feishu_bitable_app_table_field.delete":        {"base:field:delete"},
	"feishu_bitable_app_table_record.create":       {"base:record:create"},
	"feishu_bitable_app_table_record.list":         {"base:record:retrieve"},
	"feishu_bitable_app_table_record.update":       {"base:record:update"},
	"feishu_bitable_app_table_record.delete":       {"base:record:delete"},
	"feishu_bitable_app_table_record.batch_create": {"base:record:create"},
	"feishu_bitable_app_table_record.batch_update": {"base:record:update"},
	"feishu_bitable_app_table_record.batch_delete": {"base:record:delete"},
	"feishu_bitable_app_table_view.create":         {"base:view:write_only"},
	"feishu_bitable_app_table_view.get":            {"base:view:read"},
	"feishu_bitable_app_table_view.list":           {"base:view:read"},
	"feishu_bitable_app_table_view.patch":          {"base:view:write_only"},
	"feishu_drive_file.list":                       {"space:document:retrieve"},
	"feishu_drive_file.get_meta":                   {"drive:drive.metadata:readonly"},
	"feishu_drive_file.copy":                       {"docs:document:copy"},
	"feishu_drive_file.move":                       {"space:document:move"},
	"feishu_drive_file.delete":                     {"space:document:delete"},
	"feishu_drive_file.upload":                     {"drive:file:upload"},
	"feishu_drive_file.download":                   {"drive:file:download"},
	"feishu_doc_comments.list":                     {"wiki:node:read", "docs:document.comment:read"},
	"feishu_doc_comments.list_replies":             {"wiki:node:read", "docs:document.comment:read"},
	"feishu_doc_comments.create":                   {"wiki:node:read", "docs:document.comment:create"},
	"feishu_doc_comments.reply":                    {"wiki:node:read", "docs:document.comment:create"},
	"feishu_doc_comments.patch":                    {"docs:document.comment:update"},
	"feishu_doc_media.download":                    {"board:whiteboard:node:read", "docs:document.media:download"},
	"feishu_doc_media.insert":                      {"docx:document:write_only", "docs:document.media:upload"},
}

var requiredAppScopes = []string{
	"application:application:self_manage",
	"cardkit:card:read",
	"cardkit:card:write",
	"contact:contact.base:readonly",
	"docx:document:readonly",
	"im:chat:read",
	"im:chat:update",
	"im:message.group_at_msg:readonly",
	"im:message.p2p_msg:readonly",
	"im:message.pins:read",
	"im:message.pins:write_only",
	"im:message.reactions:read",
	"im:message.reactions:write_only",
	"im:message:readonly",
	"im:message:recall",
	"im:message:send_as_bot",
	"im:message:send_multi_users",
	"im:message:send_sys_msg",
	"im:message:update",
	"im:resource",
}

var sensitiveScopes = []string{
	"im:message.send_as_user",
	"space:document:delete",
	"calendar:calendar.event:delete",
	"base:table:delete",
}
